<a href="https://colab.research.google.com/github/motorio0829/Programming-for-AI-25-1/blob/main/lecturenote/%ED%8C%90%EB%8B%A4%EC%8A%A42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 결측치

## 결측치 종류


* `None` : 파이썬 결측 데이터, NumPy 연산이 불가. Pandas 객체 내에서는 NaN으로 변경됨
* `NaN` : `Not a Number`(숫자가 아님)을 나타내는 결측 수치 데이터
* `null` : 결측을 의미. None과 NaN을 포괄

In [1]:
import numpy as np
import pandas as pd

## 결측치 확인

* `.isna()` : 누락되거나, NaN인 값을 True, 아닌 경우를 False로 반환
* `.isnull()` : 누락되거나, NaN인 값을 True, 아닌 경우를 False로 반환
* `.notnull()` : 누락되거나, NaN인 값을 False, 아닌 경우를 True로 반환
* `.info` : 데이터프레임에서 변수별로 not-null 개수 확인

In [3]:
a = pd.Series([1, 2, np.nan, 4, 5, None])
a

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [5]:
a.isna() # isnull()이랑 isna()는 걍 똑같음 완전

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [6]:
a.isnull()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
!ls

drive  sample_data

In [10]:
data = pd.read_csv('/content/drive/MyDrive/AI를위한프로그래밍/dataset/train_ap_0402.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [12]:
data.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [13]:
data.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [14]:
data.Age.isna()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

## 결측치 처리


* `dropna()` : 누락된 데이터가 있는 축을 제외
* `fillna()`: 다른 값으로 치환. `ffill`이나 `bfill`로 보간 메소드 적용
<br> ffill: 앞의 값으로 보간
<br> bfill: 뒤의 값으로 보간

In [15]:
data.dropna() # na값이 포함된 모든 행을 삭제

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [16]:
data.dropna(subset=['Age','Cabin']) # 'Age', 'Cabin' 열에 Na값이 포함된 모든 행을 삭제

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [17]:
print(data.dropna(subset = ['Age', 'Cabin'])['Age'].isna().sum())
print(data.dropna(subset = ['Age', 'Cabin'])['Cabin'].isna().sum())

0
0

In [18]:
data.dropna(axis=0) # 행축을 기준으로 삭제

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [19]:
data.dropna(axis=1) # 열축을 기준으로 삭제

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

* `Age`를 평균으로 대체하기

In [20]:
data['Age'].mean()

np.float64(29.69911764705882)

In [21]:
data['Age'][data['Age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
       ..
859   NaN
863   NaN
868   NaN
878   NaN
888   NaN
Name: Age, Length: 177, dtype: float64

In [24]:
data2 = data['Age'].fillna(data['Age'].mean())

In [25]:
data2.iloc[5,] # NaN 값이 'Age' 칼럼의 mean으로 채워진 것을 볼 수 있음

np.float64(29.69911764705882)

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [27]:
data['Age'].ffill()

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    19.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [29]:
data1 = data['Age']
data2 = data['Age'].ffill() # 앞 값으로 NaN값 대체
data3 = data['Age'].bfill() # 뒤 값으로 NaN값 대체

data4 = pd.concat([data1, data2, data3], axis = 1)
data4

      Age   Age   Age
0    22.0  22.0  22.0
1    38.0  38.0  38.0
2    26.0  26.0  26.0
3    35.0  35.0  35.0
4    35.0  35.0  35.0
..    ...   ...   ...
886  27.0  27.0  27.0
887  19.0  19.0  19.0
888   NaN  19.0  26.0
889  26.0  26.0  26.0
890  32.0  32.0  32.0

[891 rows x 3 columns]

In [30]:
data['Age'].bfill()

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    26.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [31]:
data2 = data.copy()
data2.Age = data['Age'].fillna(data['Age'].mean())

In [32]:
data2.info() # null 값이 없음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

* 생존자/사망자 별 평균으로 대체하기

In [33]:
mage1 = data[data.Survived==1].Age.mean()
mage0 = data[data.Survived==0].Age.mean()
mage1, mage0

(np.float64(28.343689655172415), np.float64(30.62617924528302))

In [34]:
data[data.Survived==1].Age.fillna(mage1)

1      38.0
2      26.0
3      35.0
8      27.0
9      14.0
       ...
875    15.0
879    56.0
880    25.0
887    19.0
889    26.0
Name: Age, Length: 342, dtype: float64

In [35]:
data[data.Survived==0].Age.fillna(mage0)

0      22.000000
4      35.000000
5      30.626179
6      54.000000
7       2.000000
         ...
884    25.000000
885    39.000000
886    27.000000
888    30.626179
890    32.000000
Name: Age, Length: 549, dtype: float64

In [36]:
data3 = data.copy()
data3.loc[data['Survived']==1, 'Age'] = data[data['Survived']==1]['Age'].fillna(mage1)
data3.loc[data['Survived']==0, 'Age'] = data[data['Survived']==0]['Age'].fillna(mage0)
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [37]:
a = pd.Series([1, 2, np.nan, 4, 5, None])
a

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [38]:
a.ffill()

0    1.0
1    2.0
2    2.0
3    4.0
4    5.0
5    5.0
dtype: float64

In [39]:
a.bfill()

0    1.0
1    2.0
2    4.0
3    4.0
4    5.0
5    NaN
dtype: float64

# 범주형 데이터

* 수치형 데이터 (numerical type) : 연속성을 띄는 숫자로 이루어진 데이터 (예: Age, Fare)
* 범주형 데이터 (categorical type) : 연속적이지 않은 값. 수치형 데이터라도 개념적으로 범주형으로 처리 필요한 경우 있음 (예: Sex, PClass).

In [40]:
data = pd.read_csv('/content/drive/MyDrive/AI를위한프로그래밍/dataset/train_ap_0402.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 생성 및 변환

* `astype('category')` : 범주형 데이터로 변환. 변환 후에는 categories와 codes 속성을 가짐
* `pd.Categorical()` : 카테고리 변수 생성
* `pd.Categorical.from_codes(codes, categories)` : 코드와 카테고리 지정하여 생성

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [42]:
data.Pclass = data.Pclass.astype('category') # 카테코리 클래스로 타입 변환
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: category(1), float64(2), int64(4), object(5)
memory usage: 77.7+ KB

In [43]:
data.Pclass = data.Pclass.astype('category')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: category(1), float64(2), int64(4), object(5)
memory usage: 77.7+ KB

In [44]:
data.Pclass

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: category
Categories (3, int64): [1, 2, 3]

## 속성

* `.categories` : 카테고리 인덱스 확인.
* `.codes` : 실제 코딩 내용 확인. 단 Series의 경우 `.cat`을 붙여주어야 함

In [45]:
data.Pclass.cat.categories

Index([1, 2, 3], dtype='int64')

In [46]:
data.Pclass.cat.codes # 정수로 실제 인코딩할때의 값.
# 컴퓨터는 0부터 인식

0      2
1      0
2      2
3      0
4      2
      ..
886    1
887    0
888    2
889    0
890    2
Length: 891, dtype: int8

In [47]:
# 새로운 범주형 변수 생성
a = pd.Categorical(["a", "b", "a", "b", "c", "a"])
print(a)
print(type(a))
print(a.categories)
print(a.codes)

['a', 'b', 'a', 'b', 'c', 'a']
Categories (3, object): ['a', 'b', 'c']
<class 'pandas.core.arrays.categorical.Categorical'>
Index(['a', 'b', 'c'], dtype='object')
[0 1 0 1 2 0]

In [48]:
# 새로운 범주형 변수 지정
a = pd.Categorical(["a", "b", "a", "b", "c", "a"], categories=["a", "b", "c", "d"])
print(a)
print(type(a))
print(a.categories)
print(a.codes)

['a', 'b', 'a', 'b', 'c', 'a']
Categories (4, object): ['a', 'b', 'c', 'd']
<class 'pandas.core.arrays.categorical.Categorical'>
Index(['a', 'b', 'c', 'd'], dtype='object')
[0 1 0 1 2 0]

In [49]:
# 새로운 범주형 변수 지정 3
a = pd.Categorical.from_codes([0, 1, 0, 1, 1], categories=["death", "survived"])
# 0 - death, 1 - survived
print(a)
print(type(a))
print(a.categories)
print(a.codes)

['death', 'survived', 'death', 'survived', 'survived']
Categories (2, object): ['death', 'survived']
<class 'pandas.core.arrays.categorical.Categorical'>
Index(['death', 'survived'], dtype='object')
[0 1 0 1 1]

In [ ]:
a = pd.Categorical.from_codes([1, 2, 1, 2, 1, 1], ["male", "female"]) # '0'에 지정된 카테고리가 없으므로 오류 발생
a

ValueError: codes need to be between -1 and len(categories)-1

In [50]:
a = pd.Categorical.from_codes([1, 2, 1, 2, 1, 1], ["", "male", "female"])
a

['male', 'female', 'male', 'female', 'male', 'male']
Categories (3, object): ['', 'male', 'female']

In [51]:
help(pd.Categorical.from_codes)

Help on method from_codes in module pandas.core.arrays.categorical:

from_codes(codes, categories=None, ordered=None, dtype: 'Dtype | None' = None, validate: 'bool' = True) -> 'Self' class method of pandas.core.arrays.categorical.Categorical
    Make a Categorical type from codes and categories or dtype.

    This constructor is useful if you already have codes and
    categories/dtype and so do not need the (computation intensive)
    factorization step, which is usually done on the constructor.

    If your data does not follow this convention, please use the normal
    constructor.

    Parameters
    ----------
    codes : array-like of int
        An integer array, where each integer points to a category in
        categories or dtype.categories, or else is -1 for NaN.
    categories : index-like, optional
        The categories for the categorical. Items need to be unique.
        If the categories are not given here, then they must be provided
        in `dtype`.
    ordered : bool, optional
        Whether or not this categorical is treated as an ordered
        categorical. If not given here or in `dtype`, the resulting
        categorical will be unordered.
    dtype : CategoricalDtype or "category", optional
        If :class:`CategoricalDtype`, cannot be used together with
        `categories` or `ordered`.
    validate : bool, default True
        If True, validate that the codes are valid for the dtype.
        If False, don't validate that the codes are valid. Be careful about skipping
        validation, as invalid codes can lead to severe problems, such as segfaults.

        .. versionadded:: 2.1.0

    Returns
    -------
    Categorical

    Examples
    --------
    >>> dtype = pd.CategoricalDtype(['a', 'b'], ordered=True)
    >>> pd.Categorical.from_codes(codes=[0, 1, 0, 1], dtype=dtype)
    ['a', 'b', 'a', 'b']
    Categories (2, object): ['a' < 'b']

## 카테고리 처리

* `.set_categories()` : 새로운 카테고리로 변경
* `.add_categories()` : 기존 카테고리에 새로운 카테고리 추가
* `.rename_categories()` : 카테고리 이름 변경
* `.remove_categories()` : 카테고리 제거
* `.remove_unused_categories()` : 사용하지 않는 카테고리 제거
* `.as_ordered` : 카테고리에 순서 지정
* `.as_unordered` : 카테고리에 순서 미지정

In [67]:
a = pd.Categorical([1, 2, 1, 2, 1, 1])
a = a.set_categories([1, 2, 3])
a

[1, 2, 1, 2, 1, 1]
Categories (3, int64): [1, 2, 3]

In [68]:
a = a.add_categories([4])
a

[1, 2, 1, 2, 1, 1]
Categories (4, int64): [1, 2, 3, 4]

In [69]:
a = a.remove_categories([3])
a

[1, 2, 1, 2, 1, 1]
Categories (3, int64): [1, 2, 4]

In [70]:
a = a.remove_unused_categories()
a

[1, 2, 1, 2, 1, 1]
Categories (2, int64): [1, 2]

In [71]:
a1 = a.rename_categories(["male", "female"]); a1

['male', 'female', 'male', 'female', 'male', 'male']
Categories (2, object): ['male', 'female']

In [72]:
a2 = a.rename_categories({1:"female", 2:"male"}); a2

['female', 'male', 'female', 'male', 'female', 'female']
Categories (2, object): ['female', 'male']

In [73]:
a3 = a.as_ordered() # ordinal category
a3

[1, 2, 1, 2, 1, 1]
Categories (2, int64): [1 < 2]

In [74]:
a4 = a3.as_unordered() # nominal category
a4

[1, 2, 1, 2, 1, 1]
Categories (2, int64): [1, 2]

## 더미변수 생성

* `pd.get_dummies(data, columns=None, drop_first=False)` : 0, 1로 변환.
    * `columns` : 데이터 프레임 내에서 더미변수를 생성하기 위한 열이름 지정
    * `drop_first` : True이면 첫번째 카테고리값을 reference로 지정

![image.png]()

![image.png]()

In [75]:
a = pd.DataFrame({"NAME": ["성기훈", "오일남", "조상우", "장덕수", "강새벽"],
                  "흡연상태": ["현재흡연", "과거흡연(5년이상)", "현재흡연", "과거흡연(5년미만)", "비흡연"]})
a

  NAME        흡연상태
0  성기훈        현재흡연
1  오일남  과거흡연(5년이상)
2  조상우        현재흡연
3  장덕수  과거흡연(5년미만)
4  강새벽         비흡연

In [76]:
a["흡연상태"] = pd.Categorical(a["흡연상태"], categories=["비흡연", "과거흡연(5년미만)", "과거흡연(5년이상)", "현재흡연"])
a.흡연상태

0          현재흡연
1    과거흡연(5년이상)
2          현재흡연
3    과거흡연(5년미만)
4           비흡연
Name: 흡연상태, dtype: category
Categories (4, object): ['비흡연', '과거흡연(5년미만)', '과거흡연(5년이상)', '현재흡연']

In [77]:
pd.get_dummies(a['흡연상태'], dtype = 'int')

   비흡연  과거흡연(5년미만)  과거흡연(5년이상)  현재흡연
0    0           0           0     1
1    0           0           1     0
2    0           0           0     1
3    0           1           0     0
4    1           0           0     0

In [78]:
 pd.get_dummies(a["흡연상태"], drop_first=True) # 맨 첫 열 없애줌

   과거흡연(5년미만)  과거흡연(5년이상)   현재흡연
0       False       False   True
1       False        True  False
2       False       False   True
3        True       False  False
4       False       False  False

In [79]:
a[["x1","x2","x3"]] = pd.get_dummies(a["흡연상태"], dtype = 'int', drop_first=True)
a

  NAME        흡연상태  x1  x2  x3
0  성기훈        현재흡연   0   0   1
1  오일남  과거흡연(5년이상)   0   1   0
2  조상우        현재흡연   0   0   1
3  장덕수  과거흡연(5년미만)   1   0   0
4  강새벽         비흡연   0   0   0

# 데이터 전처리

## duplicated()

* `DataFrame.duplicated(subset=None, keep="first")`
    * 메소드가 적용된 열과 길이가 동일한 boolean 벡터를 반환
    * 어떤 요소가 중복인지 확인 가능
    * `subset` : 중복데이터를 확인할 열 지정. Series, index에 적용할 경우 사용하지 않음
    * `keep` : 중복데이터 발견 시 어떤 데이터를 마크할지 삭제할지 결정
        * `keep="first"(default)` : 처음에 발견된 데이터를 제외하고 중복인 경우 True
        * `keep="last"` : 마지막으로 발견된 데이터를 제외하고 중복인 경우 True
        * `keep=False` : 모든 중복데이터에 대해 True

* `DataFrame.drop_duplicates(subset=None, keep="first", inplace=False)`
    * `inplace=False` : 기존 데이터프레임 반영여부

In [86]:
df = pd.DataFrame(data = [[1,2,3], [1,2,4], [1,3,3], [1,2,4]], columns=["a", "b", "c"])
df

   a  b  c
0  1  2  3
1  1  2  4
2  1  3  3
3  1  2  4

In [87]:
df.duplicated()  # 각 행별로 모든 요소가 중복인지 체크
#default(keep="first") 처음 발견된 데이터 제외

0    False
1    False
2    False
3     True
dtype: bool

In [88]:
print(df.duplicated("a", keep = 'first'))  # a열 중복체크
print(df.duplicated('a', keep = 'last'))
print(df.duplicated('a', keep = False))

0    False
1     True
2     True
3     True
dtype: bool
0     True
1     True
2     True
3    False
dtype: bool
0    True
1    True
2    True
3    True
dtype: bool

In [90]:
df.duplicated(["a", "b"])  # a,b열 중복체크

0    False
1     True
2    False
3     True
dtype: bool

In [91]:
df.duplicated(["a", "b"], keep="last")

0     True
1     True
2    False
3    False
dtype: bool

In [92]:
df.drop_duplicates()

   a  b  c
0  1  2  3
1  1  2  4
2  1  3  3

In [93]:
print(df)
df.drop_duplicates("a", inplace=True)
print(df)

   a  b  c
0  1  2  3
1  1  2  4
2  1  3  3
3  1  2  4
   a  b  c
0  1  2  3

## sort()

* `DataFrame.sort_values(by=None, axis=0, ascending=True, inplace=False, na_position="last")`
    * 해당 변수의 값 기준으로 정렬
    * `by=None` : 정렬할 기준 변수 지정
    * `axis` : `0` 또는 `"index"` 입력 시 행 기준 정렬. `1` 또는 `"columns"` 입력 시 열 기준 정렬
    * `ascending` : `True`이면 오름차순, `False`이면 내림차순
    * `na_position` : 결측값 위치 ("first", "last")

* `DataFrame.sort_index(axis=0, asceding=True, inplace=False, na_position="last"))`
    * 인덱스 기준으로 정렬

In [95]:
np.random.seed(123)
df = pd.DataFrame(np.random.randint(0, 10, (4,4)),
                  index=[2, 4, 1, 3],
                  columns=list("BDAC"))
df

   B  D  A  C
2  2  2  6  1
4  3  9  6  1
1  0  1  9  0
3  0  9  3  4

In [96]:
df.sort_values(["A", "B"], ascending=[True, False])

   B  D  A  C
3  0  9  3  4
4  3  9  6  1
2  2  2  6  1
1  0  1  9  0

In [97]:
df.sort_index()

   B  D  A  C
1  0  1  9  0
2  2  2  6  1
3  0  9  3  4
4  3  9  6  1

## rank()

* `rank(method="average")`
    * 값들의 순위 지정
    * `method` : 같은 값에 대한 처리방법
        * `method="average"` : 같은 값을 가지는 항목들의 순위 평균값 사용
        * `method="min"` : 같은 값을 가지는 항목들의 순위 최소값 사용
        * `method="max"` : 같은 값을 가지는 항목들의 순위 최대값 사용
        * `method="dense"` : 같은 값을 가지는 항목들의 순위를 동일하게 하고, 전체 순위를 1씩 증가
        * `method="first"` : 같은 값을 가지는 항목들의 순위를 데이터 내 위치에 따라 1씩 증가하게 부여

In [106]:
a = pd.Series([1, 7, -3, 1, 1, 1])
pd.concat([a, a.rank()], axis = 1)
a

0    1
1    7
2   -3
3    1
4    1
5    1
dtype: int64

In [107]:
a.rank(method="min")

0    2.0
1    6.0
2    1.0
3    2.0
4    2.0
5    2.0
dtype: float64

In [108]:
a.rank(method="max")

0    5.0
1    6.0
2    1.0
3    5.0
4    5.0
5    5.0
dtype: float64

In [109]:
a.rank(method="dense")

0    2.0
1    3.0
2    1.0
3    2.0
4    2.0
5    2.0
dtype: float64

In [110]:
a.rank(method="first")

0    2.0
1    6.0
2    1.0
3    3.0
4    4.0
5    5.0
dtype: float64

In [111]:
a.cummin() #누적최소값 <=> cummax() 누적최대값
# 누적된 값 중 최소값 or 최대값 반환

0    1
1    1
2   -3
3   -3
4   -3
5   -3
dtype: int64

In [112]:
a.cummax()

0    1
1    7
2    7
3    7
4    7
5    7
dtype: int64

## set_index()

* `set_index()` : 지정한 변수를 index로 지정가능. 다중 지정 가능
* `reset_index()` : index 초기

In [113]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [114]:
data.set_index("Age").index

Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
       ...
       33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],
      dtype='float64', name='Age', length=891)

In [115]:
data.set_index(["Age", "Sex"])

             PassengerId  Survived Pclass  \
Age  Sex
22.0 male              1         0      3
38.0 female            2         1      1
26.0 female            3         1      3
35.0 female            4         1      1
     male              5         0      3
...                  ...       ...    ...
27.0 male            887         0      2
19.0 female          888         1      1
NaN  female          889         0      3
26.0 male            890         1      1
32.0 male            891         0      3

                                                          Name  SibSp  Parch  \
Age  Sex
22.0 male                              Braund, Mr. Owen Harris      1      0
38.0 female  Cumings, Mrs. John Bradley (Florence Briggs Th...      1      0
26.0 female                             Heikkinen, Miss. Laina      0      0
35.0 female       Futrelle, Mrs. Jacques Heath (Lily May Peel)      1      0
     male                             Allen, Mr. William Henry      0      0
...                                                        ...    ...    ...
27.0 male                                Montvila, Rev. Juozas      0      0
19.0 female                       Graham, Miss. Margaret Edith      0      0
NaN  female           Johnston, Miss. Catherine Helen "Carrie"      1      2
26.0 male                                Behr, Mr. Karl Howell      0      0
32.0 male                                  Dooley, Mr. Patrick      0      0

                       Ticket     Fare Cabin Embarked
Age  Sex
22.0 male           A/5 21171   7.2500   NaN        S
38.0 female          PC 17599  71.2833   C85        C
26.0 female  STON/O2. 3101282   7.9250   NaN        S
35.0 female            113803  53.1000  C123        S
     male              373450   8.0500   NaN        S
...                       ...      ...   ...      ...
27.0 male              211536  13.0000   NaN        S
19.0 female            112053  30.0000   B42        S
NaN  female        W./C. 6607  23.4500   NaN        S
26.0 male              111369  30.0000  C148        C
32.0 male              370376   7.7500   NaN        Q

[891 rows x 10 columns]

In [116]:
data1 = data.set_index(["Age", "Sex"])
data1.reset_index()

,Age,Sex,PassengerId,Survived,Pclass,Name,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,22.0,male,1,0,3,"Braund, Mr. Owen Harris",1,0,A/5 21171,7.2500,NaN,S
1,38.0,female,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,71.2833,C85,C
2,26.0,female,3,1,3,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,7.9250,NaN,S
3,35.0,female,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,53.1000,C123,S
4,35.0,male,5,0,3,"Allen, Mr. William Henry",0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,27.0,male,887,0,2,"Montvila, Rev. Juozas",0,0,211536,13.0000,NaN,S
887,19.0,female,888,1,1,"Graham, Miss. Margaret Edith",0,0,112053,30.0000,B42,S
888,NaN,female,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,2,W./C. 6607,23.4500,NaN,S
889,26.0,male,890,1,1,"Behr, Mr. Karl Howell",0,0,111369,30.0000,C148,C
890,32.0,male,891,0,3,"Dooley, Mr. Patrick",0,0,370376,7.7500,NaN,Q

## groupby()

* 지정한 카테고리별로 (1) 그룹을 나누어 (2) 집계연산을 수행한 뒤, (3) 결과를 병합
* `.groupby()`
    * 지정된 변수의 카테고리별로 그룹을 분류
    * `.groups`에 그룹과 그룹에 속한 index가 dictionary 형태로 저장

In [117]:
import numpy as np
import pandas as pd
dpath = "/content/drive/MyDrive/AI를위한프로그래밍/dataset/"

In [118]:
data = pd.read_csv(dpath + "train_ap_0402.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [119]:
a = data.groupby("Pclass") #분할만 한 것.
a

In [120]:
a.groups # 해당하는 그룹별 행 index 출력

{1: [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 2: [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 3: [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [121]:
b = data.groupby("Sex")
b.groups

{'female': [1, 2, 3, 8, 9, 10, 11, 14, 15, 18, 19, 22, 24, 25, 28, 31, 32, 38, 39, 40, 41, 43, 44, 47, 49, 52, 53, 56, 58, 61, 66, 68, 71, 79, 82, 84, 85, 88, 98, 100, 106, 109, 111, 113, 114, 119, 123, 128, 132, 133, 136, 140, 141, 142, 147, 151, 156, 161, 166, 167, 172, 177, 180, 184, 186, 190, 192, 194, 195, 198, 199, 205, 208, 211, 215, 216, 218, 229, 230, 233, 235, 237, 240, 241, 246, 247, 251, 254, 255, 256, 257, 258, 259, 264, 268, 269, 272, 274, 275, 276, ...], 'male': [0, 4, 5, 6, 7, 12, 13, 16, 17, 20, 21, 23, 26, 27, 29, 30, 33, 34, 35, 36, 37, 42, 45, 46, 48, 50, 51, 54, 55, 57, 59, 60, 62, 63, 64, 65, 67, 69, 70, 72, 73, 74, 75, 76, 77, 78, 80, 81, 83, 86, 87, 89, 90, 91, 92, 93, 94, 95, 96, 97, 99, 101, 102, 103, 104, 105, 107, 108, 110, 112, 115, 116, 117, 118, 120, 121, 122, 124, 125, 126, 127, 129, 130, 131, 134, 135, 137, 138, 139, 143, 144, 145, 146, 148, 149, 150, 152, 153, 154, 155, ...]}


* aggregation (집계) 연산

함수 | 설명
:--- | :---
`count()` | 전체 개수
`head()`, `tail()`| 항목 앞, 뒤의 5개 반환
`describe()` | Series나 DataFrame의 각 컬럼에 대한 요약 통계
`min()`, `max()` | 최소값, 최대값
`cummin()`, `cummax()` | 해당 인덱스까지 누적된 요소 중 최소값, 최대값
`argmin()`, `argmax()` | 최소값과 최대값의 인덱스 위치
`idxmin()`, `idxmax()` | 최소값과 최대값의 인덱스 값
`mean()`, `median()` | 평균, 중앙값
`var()`, `std()` | 분산, 표준편차
`sum()`, `cumsum()` | 전체 항목 합, 누적합
`prod()`, `cumprod()` | 전체 항목 곱, 누적곱
`quantile()` | 분위수
`diff()` | 차분
`cov()`, `corr()`| 공분산, 상관관계

* 성별에 따른 생존명수 계산

In [122]:
data["Survived"].groupby(data["Sex"]).sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [123]:
data.groupby("Sex").Survived.sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

* 성별에 따른 생존률 계산

In [124]:
data["Survived"].groupby(data["Sex"]).mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [125]:
data.groupby("Sex").Survived.mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

* 클래스와 성별에 따른 생존률 계산

In [126]:
data.groupby(["Pclass", "Sex"]).Survived.mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [127]:
print(type(data.groupby(["Pclass", "Sex"]).Survived.mean()))
data.groupby(["Pclass", "Sex"]).Survived.mean().index

<class 'pandas.core.series.Series'>

MultiIndex([(1, 'female'),
            (1,   'male'),
            (2, 'female'),
            (2,   'male'),
            (3, 'female'),
            (3,   'male')],
           names=['Pclass', 'Sex'])

In [132]:
data.groupby(["Pclass", "Sex"]).Survived.mean().loc[(2,"female")]
# 2번클래스 여성 생존률

np.float64(0.9210526315789473)

* Index로 지정된 변수로 groupby 적용 가능
    * `groupby(level)`에서 level은 index의 depth를 의미하며, 가장 왼쪽을 0으로 하여 1씩 증가


* 클래스 및 성별에 따른 생존율 구하기

In [133]:
data.set_index(["Pclass", "Sex"]).groupby(level=[0,1]).Survived.mean()

Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

* `.aggregate()` 또는 `.agg()` : 여러 개의 집계함수를 한꺼번에 적용

In [134]:
data.groupby(["Pclass", "Sex"]).Survived.agg(["count", "sum", "mean"])

               count  sum      mean
Pclass Sex
1      female     94   91  0.968085
       male      122   45  0.368852
2      female     76   70  0.921053
       male      108   17  0.157407
3      female    144   72  0.500000
       male      347   47  0.135447

## transform() - 원래의 인덱스를 유지하면서 집계함수 적용

* `transform()`
    * groupby와 transform 함수를 사용하면 원래의 index를 유지하면서 집계함수 적용
    * 전체 데이터의 집계가 아닌 각 그룹에서의 집계를 계산
    * 새로 생성된 데이터를 원본 dataframe과 병합 용이

In [135]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [138]:
data.groupby("Pclass").Survived.mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [139]:
data.groupby("Pclass").Survived.transform("mean")

0      0.242363
1      0.629630
2      0.242363
3      0.629630
4      0.242363
         ...
886    0.472826
887    0.629630
888    0.242363
889    0.629630
890    0.242363
Name: Survived, Length: 891, dtype: float64

In [140]:
data["Pclass_survivalrate"] = data.groupby("Pclass").Survived.transform("mean")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_survivalrate
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.242363
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.629630
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.242363
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.629630
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.242363

## stack(), unstack()

* `DataFrame.stack()` : 컬럼 레벨에서 인덱스 레벨 즉, 행방향으로 데이터 재구조화
* `DataFrame.unstack()` : 인덱스 레벨에서 컬럼레벨 즉, 열방향으로 데이터 재구조화

![image.png]()

In [141]:
a = pd.DataFrame({"Age": ["10대", "10대", "20대", "20대"],
                  "Sex": ["남성", "여성", "남성", "여성"],
                  "명수": [10, 20, 30, 40]})

print(a)
a.set_index(["Age", "Sex"], inplace=True)
a

   Age Sex  명수
0  10대  남성  10
1  10대  여성  20
2  20대  남성  30
3  20대  여성  40

         명수
Age Sex
10대 남성   10
    여성   20
20대 남성   30
    여성   40

In [142]:
a.unstack()

     명수
Sex  남성  여성
Age
10대  10  20
20대  30  40

## pivot_table()

* `pivot_table(values, index, columns, aggfunc="mean", fill_value=None, margins=False, dropna=True)`
    * 데이터프레임 재배치
    * set_index로 계층적 색인 생성 후, unstack() 메소드로 형태를 변경하는 과정을 축약한 형태

In [147]:
data.pivot_table(values = "Survived", index="Pclass", columns="Sex", aggfunc = 'mean')

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [148]:
data.pivot_table("Survived", index="Pclass", columns="Sex", aggfunc="sum")

Sex     female  male
Pclass
1           91    45
2           70    17
3           72    47

In [149]:
data.pivot_table("Survived", index="Pclass", columns="Sex", aggfunc="sum", margins=True)  # margins: 주변확률분포

Sex     female  male  All
Pclass
1           91    45  136
2           70    17   87
3           72    47  119
All        233   109  342

In [154]:
data.pivot_table(["Survived", "Fare"], index="Pclass", columns="Sex", aggfunc=["mean", "sum"]).sort_values(by = ('mean', 'Fare', 'female'), ascending = 1) # 튜플로 by에 지정
# 피벗테이블 정렬하기

              mean                                       sum             \
              Fare             Survived                 Fare
Sex         female       male    female      male     female       male
Pclass
3        16.118810  12.661633  0.500000  0.135447  2321.1086  4393.5865
2        21.970121  19.741782  0.921053  0.157407  1669.7292  2132.1125
1       106.125798  67.226127  0.968085  0.368852  9975.8250  8201.5875


       Survived
Sex      female male
Pclass
3            72   47
2            70   17
1            91   45

## concat()

* 판다스에서 데이터 붙이는 함수
    * `pd.concat()` : 지정된 축의 인덱스 기준으로 병합
    * `pd.merge()` : 지정된 컬럼을 기준으로 병합
    * `pd.DataFrame.join()` : 인덱스 기준으로 조인

* `pd.concat([data1, data2], axis=0, ignore_index=False)`
    * 데이터를 인덱스를 기준으로 행이나 열방향으로 붙임

![image.png]()

In [155]:
import numpy as np
import pandas as pd

In [156]:
data1 = pd.DataFrame({"id": [1,2,3,4,5], "test1":[60, 80, 70, 90, 85]})
data2 = pd.DataFrame({"id": [6,7,8,9,10],"test1":[70, 30, 80, 90, 100]})

In [157]:
# index가 같은 것들이 있던 말던 상관없이 단순하게 위아래로 합쳐짐.
# 공통된 내용을 가진 데이터프레임을 세로 또는 가로로 합치는 것 -> pd.concat()
pd.concat([data1, data2])

   id  test1
0   1     60
1   2     80
2   3     70
3   4     90
4   5     85
0   6     70
1   7     30
2   8     80
3   9     90
4  10    100

In [158]:
pd.concat([data1, data2], axis=1)

   id  test1  id  test1
0   1     60   6     70
1   2     80   7     30
2   3     70   8     80
3   4     90   9     90
4   5     85  10    100

In [159]:
data2.index = [1,2,3,4,5]
data2

   id  test1
1   6     70
2   7     30
3   8     80
4   9     90
5  10    100

In [160]:
# 가로로 합칠 때, index label이 같은 경우
pd.concat([data1, data2], axis=1)

    id  test1    id  test1
0  1.0   60.0   NaN    NaN
1  2.0   80.0   6.0   70.0
2  3.0   70.0   7.0   30.0
3  4.0   90.0   8.0   80.0
4  5.0   85.0   9.0   90.0
5  NaN    NaN  10.0  100.0

![image.png]()

In [161]:
data1 = pd.DataFrame({"id": [1,2,3,4,5], "test1":[60, 80, 70, 90, 85]})
data2 = pd.DataFrame({"id": [3,2,1,4,5],"test2":[70, 30, 80, 90, 100]})
data1.set_index("id", inplace=True)
data2.set_index("id", inplace=True)
data1

    test1
id
1      60
2      80
3      70
4      90
5      85

In [162]:
data2

    test2
id
3      70
2      30
1      80
4      90
5     100

In [163]:
# 같은 index label끼리 합쳐짐
pd.concat([data1, data2], axis=1)

    test1  test2
id
1      60     80
2      80     30
3      70     70
4      90     90
5      85    100

## merge()

* `pd.merge(data1, data2,left_index=False, right_index=False, how="outer", left_on=None, right_on=None, suffixes=("_x", "_y")`
    * `left_index`, `right_index` : 데이터를 인덱스를 기준으로 행이나 열방향으로 붙임
    * `left_on`, `right_on` : 데이터를 특정 변수를 기준으로 병합. 여러 개 변수 지정 가능.
    * `how` : 병합 기준. "outer", "inner", "left", "right"


* `DataFrame.join(data2, on=None, how="left", lsuffix="", rsuffix="")`
    * 데이터프레임의 메소드
    * lsuffix, rsuffix: 접두어 붙이기(구분용)

![image.png]()

In [176]:
data1 = pd.DataFrame({"id": [1,2,3,4,5], "test1":[60, 80, 70, 90, 85]})
data2 = pd.DataFrame({"id": [3,2,1,4,5],"test2":[70, 30, 80, 90, 100]})

In [177]:
data1

   id  test1
0   1     60
1   2     80
2   3     70
3   4     90
4   5     85

In [178]:
data2

   id  test2
0   3     70
1   2     30
2   1     80
3   4     90
4   5    100

In [179]:
pd.merge(data1, data2 , left_index = True, right_index = True)

   id_x  test1  id_y  test2
0     1     60     3     70
1     2     80     2     30
2     3     70     1     80
3     4     90     4     90
4     5     85     5    100

In [180]:
pd.merge(data1, data2, left_on="id", right_on="id", how="left")

   id  test1  test2
0   1     60     80
1   2     80     30
2   3     70     70
3   4     90     90
4   5     85    100

In [181]:
# join은 index 기준이라 index 세팅이 먼저 필요.
# join을 사용하기 위해서는 먼저 index 세팅이 필요하다.
data1.set_index("id", inplace=True)
data2.set_index("id", inplace=True)
data1.join(data2)

    test1  test2
id
1      60     80
2      80     30
3      70     70
4      90     90
5      85    100

![image.png]()

In [182]:
data1 = pd.DataFrame({"id":[1,2,3,4,5],
                      "class":[1,1,2,2,3],
                      "test":[60,80,70,90,85]})
data2 = pd.DataFrame({"class":[1,2,3],
                      "teacher": ["Kim", "Lee", "Park"]})
print(data1)
print(data2)

   id  class  test
0   1      1    60
1   2      1    80
2   3      2    70
3   4      2    90
4   5      3    85
   class teacher
0      1     Kim
1      2     Lee
2      3    Park

In [183]:
# concat()
df1 = data1.set_index("class")
df2 = data2.set_index("class")
print(df1)
print(df2)

       id  test
class
1       1    60
1       2    80
2       3    70
2       4    90
3       5    85
      teacher
class
1         Kim
2         Lee
3        Park

In [184]:
# pd.merge() using index
pd.merge(df1, df2, left_index=True, right_index=True)

       id  test teacher
class
1       1    60     Kim
1       2    80     Kim
2       3    70     Lee
2       4    90     Lee
3       5    85    Park

In [185]:
# pd.merge() using variable
pd.merge(data1, data2, left_on="class", right_on="class")

   id  class  test teacher
0   1      1    60     Kim
1   2      1    80     Kim
2   3      2    70     Lee
3   4      2    90     Lee
4   5      3    85    Park

In [186]:
# pd.DataFrame.join()
df1.join(df2, how="left")

       id  test teacher
class
1       1    60     Kim
1       2    80     Kim
2       3    70     Lee
2       4    90     Lee
3       5    85    Park

# 데이터 읽기 및 쓰기

## read_table()

* `pd.read_table(file, sep="\t", header="infer", na_values)`
    * `file`: 파일 경로
    * `sep` : 구분자
    * `header` : 첫 줄에 변수명이 있는 경우 자동으로 추정. 첫줄에 없는 경우 header=None 또는 header=0 입력
    * `na_values` : 결측으로 처리할 문자 적용. 디폴트로 다음과 같은 값을 모두 결측으로 처리

    ```
    ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’,     ‘1.#IND’,
    ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.
    ``

* 구글드라이브에 데이터 파일 업로드 후, temperature.txt와 humidity.txt를 읽어보자

![image.png]()

In [187]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [188]:
dpath = '/content/drive/MyDrive/AI를위한프로그래밍/dataset/0409_data_pandas/'# 폴더경로
temp = pd.read_table(dpath + "temperature.txt", sep=" ")
temp

      area  temperature
0    seoul         18.2
1  incheon         19.0
2    suwon         16.4
3  daejeon         15.8
4  kwangju         18.2
5    daegu         20.0
6    busan         15.5
7     jeju         22.0

In [189]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   area         8 non-null      object
 1   temperature  8 non-null      float64
dtypes: float64(1), object(1)
memory usage: 260.0+ bytes

In [190]:
humid = pd.read_table(dpath + "humidity.txt", sep=",")
humid

      area  humidity
0    seoul        72
1  incheon        93
2    suwon       100
3  daejeon        61
4  kwangju         .
5    daegu      20.5
6    busan      30.5
7     jeju       NaN

In [191]:
humid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   area       8 non-null      object
 1    humidity  7 non-null      object
dtypes: object(2)
memory usage: 260.0+ bytes

In [192]:
# "."을 NA로 변환하는 옵션 -> na_values
humid = pd.read_table(dpath + "humidity.txt", sep=",", na_values=".")
humid

      area   humidity
0    seoul       72.0
1  incheon       93.0
2    suwon      100.0
3  daejeon       61.0
4  kwangju        NaN
5    daegu       20.5
6    busan       30.5
7     jeju        NaN

In [194]:
humid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   area       8 non-null      object
 1    humidity  6 non-null      float64
dtypes: float64(1), object(1)
memory usage: 260.0+ bytes

## read_csv()

* `pd.read_csv(file, sep=",", "header="infer", na_values)`
    * `file`: 파일 경로
    * `sep` : 구분자
    * `header` : 첫 줄에 변수명이 있는 경우 자동으로 추정. 첫줄에 없는 경우 header=None 또는 header=0 입력
    * `na_values` : 결측으로 처리할 문자 적용. 디폴드로 다음과 같은 값을 모두 결측으로 처리

    ```
    ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’,     ‘1.#IND’,
    ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.
    ```

In [195]:
humid2 = pd.read_csv(dpath + "humidity.txt", na_values=".")
humid2

      area   humidity
0    seoul       72.0
1  incheon       93.0
2    suwon      100.0
3  daejeon       61.0
4  kwangju        NaN
5    daegu       20.5
6    busan       30.5
7     jeju        NaN

## .to_csv()

* `pd.DataFrame.to_csv(path, sep=",", na_rep="", header=True, index=True)`
    * `na_rep` : 결측치를 나타낼 문자
    * `index` : 행인덱스 기재할지 여부

In [196]:
outpath = "/content/drive/MyDrive/AI를위한프로그래밍/dataset/0409_data_pandas/"
humid2.to_csv(outpath + "humid2.csv")
humid2.to_csv(outpath + "humid2.txt", sep=" ", na_rep="NA", index=False)

## xls/xlsx 파일

* `pd.read_excel(file, sheet_name=0, header="infer"`
* `pd.DataFrame.to_excel(file, sheet_name="Sheet1", header=True, index=True)`

![image.png]()

In [197]:
temp = pd.read_excel(dpath + "temperature.xlsx", "temperature")
temp

      area  temperature
0    seoul         18.2
1  incheon         19.0
2    suwon         16.4
3  daejeon         15.8
4  kwangju         18.2
5    daegu         20.0
6    busan         15.5
7     jeju         22.0

In [198]:
humid = pd.read_excel(dpath + "temperature.xlsx", 1)
humid

      area  humidity
0    seoul      72.0
1  incheon      93.0
2    suwon     100.0
3  daejeon      61.0
4  kwangju       NaN
5    daegu      20.5
6    busan      30.5
7     jeju       NaN

In [199]:
humid.to_excel(outpath + "humid.xlsx", "humidity")

<ipython-input-199-becdb72a04ed>:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  humid.to_excel(outpath + "humid.xlsx", "humidity")

In [200]:
temp.to_excel(outpath + "humid.xlsx", "temperature", index=False)

<ipython-input-200-6d6e077eb5ca>:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  temp.to_excel(outpath + "humid.xlsx", "temperature", index=False)

# **THE END**